/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RezervariRouteImport } from './routes/rezervari'
import { Route as PacheteRouteImport } from './routes/pachete'
import { Route as EvenimenteRouteImport } from './routes/evenimente'
import { Route as DespreNoiRouteImport } from './routes/despre-noi'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const RezervariRoute = RezervariRouteImport.update({
  id: '/rezervari',
  path: '/rezervari',
  getParentRoute: () => rootRouteImport,
} as any)
const PacheteRoute = PacheteRouteImport.update({
  id: '/pachete',
  path: '/pachete',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenimenteRoute = EvenimenteRouteImport.update({
  id: '/evenimente',
  path: '/evenimente',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreNoiRoute = DespreNoiRouteImport.update({
  id: '/despre-noi',
  path: '/despre-noi',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/despre-noi': typeof DespreNoiRoute
  '/evenimente': typeof EvenimenteRoute
  '/pachete': typeof PacheteRoute
  '/rezervari': typeof RezervariRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/despre-noi': typeof DespreNoiRoute
  '/evenimente': typeof EvenimenteRoute
  '/pachete': typeof PacheteRoute
  '/rezervari': typeof RezervariRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/despre-noi': typeof DespreNoiRoute
  '/evenimente': typeof EvenimenteRoute
  '/pachete': typeof PacheteRoute
  '/rezervari': typeof RezervariRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/despre-noi'
    | '/evenimente'
    | '/pachete'
    | '/rezervari'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/despre-noi'
    | '/evenimente'
    | '/pachete'
    | '/rezervari'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/despre-noi'
    | '/evenimente'
    | '/pachete'
    | '/rezervari'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DespreNoiRoute: typeof DespreNoiRoute
  EvenimenteRoute: typeof EvenimenteRoute
  PacheteRoute: typeof PacheteRoute
  RezervariRoute: typeof RezervariRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rezervari': {
      id: '/rezervari'
      path: '/rezervari'
      fullPath: '/rezervari'
      preLoaderRoute: typeof RezervariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pachete': {
      id: '/pachete'
      path: '/pachete'
      fullPath: '/pachete'
      preLoaderRoute: typeof PacheteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenimente': {
      id: '/evenimente'
      path: '/evenimente'
      fullPath: '/evenimente'
      preLoaderRoute: typeof EvenimenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre-noi': {
      id: '/despre-noi'
      path: '/despre-noi'
      fullPath: '/despre-noi'
      preLoaderRoute: typeof DespreNoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DespreNoiRoute: DespreNoiRoute,
  EvenimenteRoute: EvenimenteRoute,
  PacheteRoute: PacheteRoute,
  RezervariRoute: RezervariRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
